apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: intel-rh-partner-TENANT_SLUG
  labels:
    tenant: TENANT_SLUG
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "32Gi"
    limits.cpu: "16"
    limits.memory: "64Gi"
    pods: "20"
    persistentvolumeclaims: "5"
