apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpu-runtime-model-cache
  namespace: intel-cpu-runtime-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
  resources:
    requests:
      storage: 100Gi

