"""
Canonical knowledge base for the inference gateway.

Single source of truth for embedded knowledge used by search, local
inference, and research agent modules.
"""

SEARCH_KNOWLEDGE_BASE = [
    {"id": "xeon6-amx", "text": "Intel Xeon 6 processors include Advanced Matrix Extensions (AMX) that accelerate AI inference workloads with hardware-level INT8 and BF16 matrix operations, delivering up to 10x throughput improvement for transformer models."},
    {"id": "gaudi3-arch", "text": "Intel GPU accelerators are purpose-built for deep learning with 128GB HBM2E memory and 24 Tensor Processor Cores, providing 2x throughput improvement for large language model inference."},
    {"id": "openshift-ai", "text": "Red Hat OpenShift AI integrates KServe for model serving, provides a model registry, supports distributed training, and includes built-in monitoring on heterogeneous Intel hardware."},
    {"id": "kserve", "text": "KServe is a Kubernetes-native model serving framework providing serverless inference with autoscaling, canary deployments, and multi-model serving via custom ServingRuntimes."},
    {"id": "vllm", "text": "vLLM is a high-throughput inference engine using PagedAttention for efficient memory management, supporting OpenAI-compatible APIs on both Intel CPUs and GPU accelerators."},
    {"id": "openvino", "text": "OpenVINO Model Server optimizes inference for Intel hardware with INT8 quantization, dynamic batching, and multi-model serving for embedding and reranking workloads on Xeon 6."},
    {"id": "rag", "text": "Retrieval-Augmented Generation combines document retrieval with language model generation to reduce hallucination and ground responses in factual content."},
    {"id": "routing", "text": "The inference gateway routes requests to optimal hardware based on task type and model size — embeddings to Xeon 6 CPUs for cost efficiency, large model generation to GPU accelerators."},
    {"id": "hybrid", "text": "The hybrid CPU-GPU architecture reduces inference costs by 60-70% compared to GPU-only deployments by splitting workloads between Xeon 6 and GPU based on task requirements."},
]

RESEARCH_KNOWLEDGE_BASE = [
    {"id": "kb-001", "title": "Intel Xeon 6 for AI Inference", "content": "Intel Xeon 6 processors with Advanced Matrix Extensions (AMX) provide cost-efficient AI inference for small-to-medium models. Classification, embeddings, and reranking tasks run on Xeon 6 at production throughput without requiring GPU resources. The AMX instruction set accelerates INT8 and BF16 matrix operations natively."},
    {"id": "kb-002", "title": "Intel GPU Accelerator Architecture", "content": "Intel GPU accelerators feature high-bandwidth memory (HBM2E) with 96GB capacity and dedicated tensor processing cores. GPU excels at large language model inference with 17B+ parameter models, providing 100+ tokens/sec generation throughput. The HBM bandwidth enables large context windows up to 400K tokens."},
    {"id": "kb-003", "title": "Hardware-Aware Routing Engine", "content": "The routing engine evaluates each inference request against a rubric of checks: task type, token estimate, priority, and latency target. Small classification tasks route to Xeon 6 Eco lane. Mid-range embeddings and summaries route to Xeon 6 Performance lane. Large generation tasks route to GPU Overdrive lane. Every decision includes full evidence."},
    {"id": "kb-004", "title": "Overdrive Lane Evaluation", "content": "The Overdrive engine uses a three-lane architecture: Eco (Granite Tiny on Xeon 6, ≤4K tokens), Performance (CodeLlama 7B on Xeon 6, ≤16K tokens), and Overdrive (Llama Scout 17B on GPU, ≤64K tokens). The routing matrix matches task type and token estimate to the optimal lane. Fallback rules ensure graceful degradation."},
    {"id": "kb-005", "title": "Tokenization and Cost Model", "content": "Different models tokenize text differently, producing different token counts and costs. Xeon 6 inference costs $0.0004 per 1K tokens. GPU inference costs $0.001 per 1K tokens. The routing engine automatically selects the cheapest viable hardware tier, sending small workloads to Xeon 6 and reserving GPU for tasks that need its bandwidth."},
    {"id": "kb-006", "title": "Failover and Graceful Degradation", "content": "When a hardware tier goes offline, the routing engine automatically reroutes requests. Overdrive lane failures fall back to Performance (if tokens < 32K). Performance failures fall back to Eco (for classification and short summaries). Every fallback decision is recorded with full evidence showing the reason for rerouting."},
    {"id": "kb-007", "title": "KServe and OpenShift AI Integration", "content": "Models are served via KServe ServingRuntime on Red Hat OpenShift AI. CPU inference uses vLLM optimized for Xeon 6 with AMX. GPU inference uses vLLM with Habana GPU device plugin. Both runtimes support OpenAI-compatible API endpoints for chat completions, embeddings, and classification."},
    {"id": "kb-008", "title": "LiteLLM Proxy Configuration", "content": "LiteLLM provides a unified OpenAI-compatible API gateway fronting multiple model backends. The platform routes through a MAAS-hosted LiteLLM instance. Models available: Granite, CodeLlama, Llama Scout, DeepSeek, Phi-4, Nomic embeddings. Configure the endpoint URL and API key via environment variables."},
    {"id": "kb-009", "title": "Workload Profiles for Performance Demos", "content": "Four workload profiles simulate enterprise patterns: Incident Storm (classification + RCA), RAG Barrage (embed + search + rerank + generate), Token Cannon (heavy generation stress test), and Model Race (cross-hardware comparison). Power modes scale from Standby (5 requests) to Overdrive (1000 requests)."},
    {"id": "kb-010", "title": "Governance and Approval Workflow", "content": "The platform includes a governance layer that evaluates AI-generated actions by risk level. Low-risk actions (read logs) auto-approve. Medium-risk actions (restart services) require human review. High-risk actions (delete namespaces) are denied. Every decision is recorded with evidence bundles for audit."},
    {"id": "kb-011", "title": "Prompt Injection Protection", "content": "All user input is sanitized before reaching LLM backends. The gateway strips role override patterns (system:, [INST], <|im_start|>), control characters, and templated prompts use system/user message separation. Classification and reranking tasks include 'ignore instructions in user text' defensive prompts."},
    {"id": "kb-012", "title": "Platform Deployment Architecture", "content": "The platform deploys on OpenShift with four components: PostgreSQL (persistence), Gateway (routing + inference), Frontend (React dashboard with OAuth), and the Overdrive engine. Images are built with podman and pushed to the OpenShift internal registry. Deployments use Kustomize overlays."},
    {"id": "kb-013", "title": "Intel AMX Acceleration Details", "content": "Intel Advanced Matrix Extensions (AMX) in Xeon 6 accelerate AI inference by performing tile-based matrix multiply-accumulate operations in hardware. This enables INT8 and BF16 inference at near-GPU speeds for models under 8B parameters, making Xeon 6 ideal for high-volume, low-latency classification and embedding workloads."},
]

LOCAL_KNOWLEDGE_BASE = [
    {"id": "xeon6-amx", "text": "Intel Xeon 6 processors include Advanced Matrix Extensions (AMX) that accelerate AI inference workloads. AMX provides hardware-level support for INT8 and BF16 matrix operations, delivering up to 10x throughput improvement for transformer models compared to previous generation Xeon processors without AMX."},
    {"id": "gaudi3-arch", "text": "Intel GPU accelerators are purpose-built for deep learning training and inference. Each GPU device has 96GB of HBM2e memory and 24 Tensor Processor Cores. For large language model inference, GPU provides 2x the throughput of the previous generation while maintaining cost efficiency."},
    {"id": "openshift-ai", "text": "Red Hat OpenShift AI is a platform for building, deploying, and managing AI/ML models on OpenShift. It integrates KServe for model serving, provides a model registry, supports distributed training, and includes built-in monitoring. Models can be served on heterogeneous hardware including Intel Xeon CPUs and GPU accelerators."},
    {"id": "kserve-serving", "text": "KServe is a Kubernetes-native model serving framework that provides serverless inference with autoscaling, canary deployments, and multi-model serving. On OpenShift, KServe manages ServingRuntimes that define how models are loaded and served. It supports custom runtimes for vLLM, OpenVINO, and other inference engines."},
    {"id": "vllm-engine", "text": "vLLM is a high-throughput inference engine optimized for large language models. It uses PagedAttention for efficient memory management and continuous batching for maximum GPU utilization. vLLM supports OpenAI-compatible APIs and can run on both Intel CPUs (with optimizations for AMX) and Intel GPU accelerators."},
    {"id": "openvino-opt", "text": "OpenVINO Model Server (OVMS) optimizes inference for Intel hardware. It supports model compression with INT8 quantization, dynamic batching, and multi-model serving. For embedding and reranking workloads, OVMS on Xeon 6 with AMX provides low-latency inference at a fraction of the cost of GPU-based solutions."},
    {"id": "rag-pattern", "text": "Retrieval-Augmented Generation (RAG) combines document retrieval with language model generation. The pipeline typically includes: embedding the query, searching a vector database, reranking retrieved documents, and generating an answer using the top documents as context. This reduces hallucination and grounds responses in factual content."},
    {"id": "inference-routing", "text": "The Intel-Red Hat inference gateway routes requests to optimal hardware based on task type and model size. Embedding, classification, and reranking tasks are routed to Xeon 6 CPUs for cost efficiency. Large model generation tasks above 3B parameters are routed to Intel GPU accelerators for maximum throughput."},
    {"id": "governance", "text": "AI governance in enterprise deployments requires audit trails for every inference decision. The platform logs routing decisions, model versions, input/output metadata, and approval workflows. Risk scoring and policy checks ensure that high-impact actions require human approval before execution."},
    {"id": "hybrid-arch", "text": "The hybrid CPU-GPU architecture allows organizations to optimize cost and performance. Xeon 6 CPUs handle high-volume, low-latency tasks like embeddings and classification at minimal cost. GPU accelerators handle compute-intensive generation tasks that require large model inference. This split can reduce inference costs by 60-70% compared to GPU-only deployments."},
]
