FROM registry.access.redhat.com/ubi9/python-311:latest

WORKDIR /opt/app-root/src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY router.py .

USER 1001
EXPOSE 8899

ENTRYPOINT ["python3", "router.py"]
