apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-rh-demo
resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - gateway-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - route.yaml
  - configmap.yaml
  - oauth-proxy.yaml
  - postgres-backup.yaml
commonLabels:
  app.kubernetes.io/part-of: intel-rh-ai-platform
