apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: intel-rh-demo
spec:
  selector:
    app: inference-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: intel-rh-demo
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: frontend-tls
spec:
  selector:
    app: inference-frontend
  ports:
    - name: proxy
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: intel-rh-demo
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
