---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: intel-rh-cpu-inference
  labels:
    app.kubernetes.io/name: model-cache
    platform: intel-xeon6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
