---
- name: Delete namespace
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ intel_rh_inference_namespace }}"

- name: remove_workload tasks complete
  ansible.builtin.debug:
    msg: "Removed namespace {{ intel_rh_inference_namespace }} and all resources"
  when: not silent | bool
