---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: intel-rh-gaudi-inference
  labels:
    app.kubernetes.io/name: model-cache
    platform: intel-gaudi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
