---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intel-rh-inference-gateway

resources:
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: intel-rh-ai-platform

commonAnnotations:
  platform.intel.com/component: observability
